### ISSUE TITLE
Fresh install - imports broken

### ISSUE THREAD

**Issue by BenVanCitters** [RidersDiscountCom/HypChat#33]
Here's what I get when (on OSX Mavericks) I try to import hypchat or try to run any of the example scripts from a fresh install (sudo python setup.py install):

$ python histtest.py 
Traceback (most recent call last):
  File "histtest.py", line 4, in <module>
    from hypchat import *
  File "/Users/benvancitter/Downloads/HypChat-master/hypchat/__init__.py", line 9, in <module>
    from .requests import Requests, BearerAuth, HttpTooManyRequests
  File "/Users/benvancitter/Downloads/HypChat-master/hypchat/requests.py", line 2, in <module>
    import requests
ImportError: No module named requests

**Comment by astronouth7303** [comment]
What was the output of the installation command?

**Comment by BenVanCitters** [comment]
HypChat-master benvancitter$ sudo python setup.py install
Password:
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
creating /Library/Python/2.7/site-packages/hypchat
copying build/lib/hypchat/__init__.py -> /Library/Python/2.7/site-packages/hypchat
copying build/lib/hypchat/__main__.py -> /Library/Python/2.7/site-packages/hypchat
copying build/lib/hypchat/requests.py -> /Library/Python/2.7/site-packages/hypchat
copying build/lib/hypchat/restobject.py -> /Library/Python/2.7/site-packages/hypchat
byte-compiling /Library/Python/2.7/site-packages/hypchat/__init__.py to __init__.pyc
byte-compiling /Library/Python/2.7/site-packages/hypchat/__main__.py to __main__.pyc
byte-compiling /Library/Python/2.7/site-packages/hypchat/requests.py to requests.pyc
byte-compiling /Library/Python/2.7/site-packages/hypchat/restobject.py to restobject.pyc
running install_egg_info
Writing /Library/Python/2.7/site-packages/hypchat-0.18-py2.7.egg-info

**Comment by astronouth7303** [comment]
Setup `pip` and install with `sudo pip install hypchat`. You're likely missing setuptools.

**Comment by successamp** [comment]
I'm going to assume that this issue is resolved.  Please feel free to comment again if this needs to be opened back up.
