### ISSUE TITLE
Any way to use room notification tokens?

### ISSUE THREAD

**Issue by ferrouswheel** [RidersDiscountCom/HypChat#34]
Not quite sure how to use this plugin with a "room notification token" if it is indeed possible. I get the following error...

```python
> hc.get_room('development')
HttpForbidden: {
  "error": {
    "code": 403,
    "message": "This action requires one of the following scopes: [u'view_group']",
    "type": "Forbidden"
  }
}
```

Using my personal bearer token works, but I just want to send notifications to a room, not give an app full access to our hipchat account, or have it tied to my personal account.

Adding a note in the README about it only supporting the use of full access tokens might save people tripping over this in future. In the mean time I'll just directly access the API using requests. :-)

**Comment by astronouth7303** [comment]
Duplicate of #22.

**Comment by astronouth7303** [comment]
The short version: It's not really supported, and there's not an obvious solution.

**Comment by ferrouswheel** [comment]
Cheers for the quick reply.
