### ISSUE TITLE
notify doesn't work

### ISSUE THREAD

**Issue by audleman** [RidersDiscountCom/HypChat#35]
I'm trying to use the notification endpoint with notify=True but notifications never happen. I was wondering if it was a bug or something simple I'm missing.

Here's my call:
```
room.notification('my message', notify=True, color=color)
```

Tracing down the code here's my ```data```  in ```hypchat/__init__.py(70)post()```

```
'{"color": "green", "message": "my message", "notify": true, "message_format": "html"}'
```

It's valid json, I can json.loads on it and get True for notify.

**Comment by astronouth7303** [comment]
What's the server response you get?

**Comment by successamp** [comment]
I'm going to assume that this issue is resolved.  Please feel free to comment again if this needs to be opened back up.

**Comment by audleman** [comment]
Sorry, I never found the time to trace deeper. If I have the time I'll do some tracing myself, and perhaps submit a pull request.
