### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by rjhunter** [RidersDiscountCom/HypChat#42]
From https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
"Python 3 disallows mixing the use of tabs and spaces for indentation."

```
$ pwd
/tmp/hypchat-0.19/hypchat

$ python --version
Python 3.4.3

$ python restobject.py 
  File "restobject.py", line 211
    def save(self):
                  ^
TabError: inconsistent use of tabs and spaces in indentation

$ head -n211 restobject.py | tail -n1 | od -a
0000000  sp  ht   d   e   f  sp   s   a   v   e   (   s   e   l   f   )
0000020   :  nl
0000022

$ head -n216 restobject.py | tail -n1 | od -a
0000000  sp  ht  ht   h   e   a   d   e   r   s  sp   =  sp   {   '   c
0000020   o   n   t   e   n   t   -   t   y   p   e   '   :  sp   '   a
0000040   p   p   l   i   c   a   t   i   o   n   /   j   s   o   n   '
0000060   }  nl
0000062
```

**Comment by successamp** [comment]
@rjhunter Would you please try out the branch https://github.com/RidersDiscountCom/HypChat/tree/convert_all_files_to_spaces and let me know if the problem is solved?  I ran a code formatter and set everything to use spaces instead of tabs.  This should take care of the issue.

**Comment by rjhunter** [comment]
@successamp, I successfully tested the convert_all_files_to_spaces branch.  Thanks!

**Comment by successamp** [comment]
Sounds good.  I'll go ahead and merge this in and release v0.20 shortly.
